imports:
    - { resource: tables.yml }

services:
    orynider.custom_headernfo.listener:
        class: orynider\custom_headernfo\event\listener
        arguments:
            - '@dbal.conn'        
            - '@user'
            - '@cache'
            - '@config'
            - '@template'
            - '@controller.helper'            
            - '@request'
            - '@pagination'
            - '@ext.manager'
            - '@path_helper'
            - '%core.php_ext%'
            - '%core.root_path%' 
            - '%orynider.custom_headernfo.table.custom_header_info%'
            - '%orynider.custom_headernfo.table.custom_header_info_config%'
            - '@?phpbb.collapsiblecategories.operator'            
        tags:
            - { name: event.listener }
    orynider.custom_headernfo.controller.admin.controller:
        class: orynider\custom_headernfo\controller\admin_controller
        arguments:
            - '@template'
            - '@user'
            - '@log'
            - '@cache'
            - '@dbal.conn'
            - '@request'
            - '@pagination'
            - '@ext.manager'
            - '@path_helper'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '%orynider.custom_headernfo.table.custom_header_info%'
            - '%orynider.custom_headernfo.table.custom_header_info_config%'
            - '@?files.factory'
    orynider.custom_headernfo.controller.thumbnail:
        class: orynider\custom_headernfo\controller\thumbnail
        arguments:
            - '@template'
            - '@user'
            - '@log'
            - '@cache'
            - '@dbal.conn'
            - '@request'
            - '@pagination'
            - '@ext.manager'
            - '@path_helper'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '%orynider.custom_headernfo.table.custom_header_info%'
            - '%orynider.custom_headernfo.table.custom_header_info_config%'
            - '@?files.factory'