imports:
    - { resource: tables.yml }

services:
    orynider.customheadernfo.listener:
        class: orynider\customheadernfo\event\listener
        arguments:
            - '@dbal.conn'        
            - '@user'
            - '@cache'
            - '@config'
            - '@template'
            - '@controller.helper'            
            - '@request'
            - '@pagination'
            - '@ext.manager'
            - '@path_helper'
            - '%core.php_ext%'
            - '%core.root_path%' 
            - '%orynider.customheadernfo.table.custom_header_info%'
            - '%orynider.customheadernfo.table.custom_header_info_config%'
            - '@language'			
            - '@?phpbb.collapsiblecategories.operator'            
        tags:
            - { name: event.listener }
    orynider.customheadernfo.controller.admin.controller:
        class: orynider\customheadernfo\controller\admin_controller
        arguments:
            - '@template'
            - '@user'
            - '@log'
            - '@cache'
            - '@dbal.conn'
            - '@request'
            - '@pagination'
            - '@ext.manager'
            - '@path_helper'
            - '@language'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '%orynider.customheadernfo.table.custom_header_info%'
            - '%orynider.customheadernfo.table.custom_header_info_config%'
            - '@?files.factory'
            - '@config'
    orynider.customheadernfo.controller.thumbnail:
        class: orynider\customheadernfo\controller\thumbnail
        arguments:
            - '@config'
            - '@language'
            - '@template'
            - '@user'
            - '@log'
            - '@cache'
            - '@dbal.conn'
            - '@request'
            - '@pagination'
            - '@ext.manager'
            - '@path_helper'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '%orynider.customheadernfo.table.custom_header_info%'
            - '%orynider.customheadernfo.table.custom_header_info_config%'
            - '@?files.factory'